# Generated by Django 2.2.8 on 2019-12-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191222_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='smalldesc',
            new_name='description',
        ),
    ]
